apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-external
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    targetPort: web
    nodePort: 31093
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: ClientIP
