apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: sock-shop
  name: sockshop-mysql
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: mysql
  selector:
    matchLabels:
      k8s-app: sock-shop
