apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sockshop-rabbitmq
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: rabbit-exporter
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      k8s-app: sock-shop
