apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sockshop-mongo
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: mongodb-exporter
  selector:
    matchLabels:
      k8s-app: sock-shop
