apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-external
  namespace: jaeger
  labels:
    app: jaeger
    jaeger-infra: jaeger-service
spec:
  type: NodePort
  ports:
  - name: query-http
    protocol: TCP
    port: 80
    targetPort: 16686
    nodePort: 31686
  selector:
    jaeger-infra: jaeger-pod
