---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
    k8s-app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: sock-port
    port: 3306
    targetPort: 3306
  selector:
    name: catalogue-db
