---
apiVersion: v1
kind: Service
metadata:
  name: front-end-external
  labels:
    name: front-end
    k8s-app: sock-shop
  namespace: sock-shop
spec:
  type: NodePort
  ports:
  - name: sock-port
    protocol: TCP
    port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end