---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    name: payment
    k8s-app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: sock-port
    port: 80
    targetPort: 80
  selector:
    name: payment
