---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    name: queue-master
    k8s-app: sock-shop
  annotations:
    prometheus.io/path: "/prometheus"
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: sock-port
    port: 80
    targetPort: 80
  selector:
    name: queue-master
