---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    name: user-db
    k8s-app: sock-shop
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: sock-port
    port: 27017
    targetPort: 27017
  selector:
    name: user-db

