---
apiVersion: v1
kind: Service
metadata:
  name: weave-external
  labels:
    app: weave-scope
  namespace: weave
spec:
  type: NodePort
  ports:
  - name: sock-port
    protocol: TCP
    port: 80
    targetPort: 4040
    nodePort: 31440
  selector:
    name: weave-scope-app