apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: sock-shop
  name: sock-services
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: sock-port
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      k8s-app: sock-shop
