apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: sockshop-alertrules
  namespace: monitoring
spec:
  groups:
  - name: sockshop-alertrules
    rules:
    - alert: HighErrorRate
      annotations:
        message: Rate of HTTP 500 errors per 5 minutes in service {{ $labels.service }} is {{ $value }}.
      expr: |
        rate(request_duration_seconds_count{status_code="500"}[5m]) > 1
      for: 5m
      labels:
        severity: warning
